name = "MSLProcessBackend"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version = "1.0.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"
DICOM = "a26e6606-dd52-5f6a-a97f-4f611373d757"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.9"